name: Build and Release YTMusicUltimate

on:
  workflow_dispatch:
    inputs: 
      ipa_url:
        description: "URL to the decrypted IPA file"
        default: ""
        required: true
        type: string

      enable_rymd:
        description: "Integrate Return YouTube Music Dislikes"
        type: boolean
        required: true
        default: true

      display_name:
        description: "App Name (Optional)"
        default: "YouTube Music"
        required: true
        type: string

      bundle_id:
        description: "BundleID (Optional)"
        default: "com.google.ios.youtubemusic"
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build YTMusicUltimate
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Main
        uses: actions/checkout@v4.1.1
        with:
          path: main
          submodules: recursive

      - name: Hide sensitive inputs
        uses: levibostian/action-hide-sensitive-inputs@v1

      - name: Validate IPA URL
        run: |
          curl -L -r 0-1023 -o sample.part "${{ inputs.ipa_url }}" > /dev/null 2>&1
          file_type=$(file --mime-type -b sample.part)

          if [[ "$file_type" != "application/x-ios-app" && "$file_type" != "application/zip" ]]; then
            echo "::error::Validation failed: The file is not a valid IPA file. Detected type: $file_type."
            exit 1
          fi

      - name: Install Dependencies
        run: brew install make ldid

      - name: Set PATH environment variable
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Cache Theos
        id: theos
        uses: actions/cache@v4.2.3
        env:
          cache-name: theos_cache_67db2ab
        with:
          path: theos/
          key: ${{ env.cache-name }}
          restore-keys: ${{ env.cache-name }}

      - name: Setup Theos
        if: steps.theos.outputs.cache-hit != 'true'
        uses: actions/checkout@v4.1.7
        with:
          repository: theos/theos
          ref: 67db2ab8d950910161730de77c322658ea3e6b44
          path: ${{ github.workspace }}/theos
          submodules: recursive

      - name: Download iOS SDK
        if: steps.theos.outputs.cache-hit != 'true'
        run: |
          git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
          cd sdks
          git sparse-checkout set --no-cone iPhoneOS16.5.sdk
          git checkout
          mv *.sdk $THEOS/sdks
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Install cyan
        run: pipx install --force https://github.com/asdfzxcvbn/pyzule-rw/archive/main.zip

      - name: Download YouTube Music
        id: download_youtube_music
        run: wget "${{ inputs.ipa_url }}" --no-verbose -O ${{ github.workspace }}/ytm.ipa

      - name: Clone PSHeader
        if: ${{ inputs.enable_rymd }}
        run: |
          if [ -d "$THEOS/include/PSHeader" ]; then
            echo "PSHeader exists. Pulling latest changes..."
            cd $THEOS/include/PSHeader
            git pull
          else
            echo "PSHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/PSHeader.git
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone Return-YouTube-Dislikes
        if: ${{ inputs.enable_rymd }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Dislikes.git

      - name: Clone YouTubeHeader
        if: ${{ inputs.enable_rymd }}
        run: |
          if [ -d "$THEOS/include/YouTubeHeader" ]; then
            echo "YouTubeHeader exists. Pulling latest changes..."
            cd $THEOS/include/YouTubeHeader
            git pull
          else
            echo "YouTubeHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeHeader.git
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone YouTubeMusicHeader
        if: ${{ inputs.enable_rymd }}
        run: |
          if [ -d "$THEOS/include/YouTubeMusicHeader" ]; then
            echo "YouTubeMusicHeader exists. Pulling latest changes..."
            cd $THEOS/include/YouTubeMusicHeader
            git pull
          else
            echo "YouTubeMusicHeader does not exist. Cloning repository..."
            cd $THEOS/include
            git clone --quiet --depth=1 https://github.com/PoomSmart/YouTubeMusicHeader.git
          fi
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Clone Return-YouTube-Music-Dislikes
        if: ${{ inputs.enable_rymd }}
        run: |
          cd ${{ github.workspace }}
          git clone --quiet --depth=1 https://github.com/PoomSmart/Return-YouTube-Music-Dislikes.git

      - name: Build Return-YouTube-Music-Dislikes
        if: ${{ inputs.enable_rymd }}
        run: |
          cd ${{ github.workspace }}/Return-YouTube-Music-Dislikes
          make clean package DEBUG=0 FINALPACKAGE=1
          mv packages/*.deb ${{ github.workspace }}/rymd.deb
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Build Tweak for Sideloading
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          make clean package SIDELOADING=1
          mv packages/*.deb ${{ github.workspace }}/ymu.deb
        env:
          THEOS: ${{ github.workspace }}/theos
 

      - name: Inject tweaks into IPA
        run: |
          tweaks="ymu.deb"

          for deb in rymd.deb ; do
            if [ -f "$deb" ]; then
              tweaks="$tweaks $deb"
            fi
          done
          

          cyan -i ytm.ipa -o YouTubeMusicUltimate_${{ inputs.tweak_version }}.ipa -uwef $tweaks -n "${{ inputs.display_name }}" -b ${{ inputs.bundle_id }}


      - name: Create Release
        uses: softprops/action-gh-release@v2.0.6
        with:
          name: YTMusicUltimate-v${{ github.run_number }}
          files: YouTubeMusicUltimate_${{ inputs.tweak_version }}.ipa
          draft: true

      - name: Output Release URL
        run: |
          echo "::notice::Release available at: https://github.com/${{ github.repository }}/releases"
